{{- if .Values.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.clusterRole.name | default (include "containerinfo.fullname" .)}}
  labels:
    {{- include "containerinfo.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "list"
{{- end }}
