apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: containerinfo
subjects:
  - kind: ServiceAccount
    name: containerinfo
    namespace: default
roleRef:
  kind: ClusterRole
  name: containerinfo
  apiGroup: rbac.authorization.k8s.io
