apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-monitor
subjects:
  - kind: ServiceAccount
    name: containerinfo
    namespace: default
roleRef:
  kind: ClusterRole
  name: pod-monitor
  apiGroup: rbac.authorization.k8s.io
